source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.4.0')
  gem "abbrev"
  gem "base64"
  gem "bigdecimal"
  gem "csv"
  gem "drb"
  gem "getoptlong"
  gem "mutex_m"
  gem "nkf"
  gem "observer"
  gem "resolv-replace"
  gem "rinda"
  gem "syslog"
end

