source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "abbrev"
gem "base64"
gem "bigdecimal"
gem "csv"
gem "drb"
gem "English"
gem "fileutils"
gem "find"
gem "getoptlong"
gem "logger"
gem "mutex_m"
gem "observer"
gem "open-uri"
gem "optparse"
gem "pp"
gem "prettyprint"
gem "rdoc"
gem "resolv"
gem "resolv-replace"
gem "set"
gem "shellwords"
gem "tempfile"
gem "time"
gem "tmpdir"
gem "weakref"
gem "yaml"


group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
