# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"
gem "sinatra", "~> 2.2.0"
gem "webrick", "~> 1.7"

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.4.0')
  gem "abbrev"
  gem "base64"
  gem "bigdecimal"
  gem "csv"
  gem "drb"
  gem "getoptlong"
  gem "mutex_m"
  gem "nkf"
  gem "observer"
  gem "resolv-replace"
  gem "rinda"
  gem "syslog"
end

