# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"
gem "functions_framework", "~> 0.5.2"
gem "webrick", "~> 1.7"
gem "base64", ">= 0"
gem "bigdecimal", ">= 0"
gem "csv", ">= 0"
gem "drb", ">= 0"
gem "getoptlong", ">= 0"
gem "mutex_m", ">= 0"
gem "nkf", ">= 0"
gem "observer", ">= 0"
gem "resolv-replace", ">= 0"
gem "rinda", ">= 0"
gem "syslog", ">= 0"
gem "abbrev", ">= 0"
